---
title: "Feature selection and machine learning models"
output: html_document
---

```{r loadInformations, message = FALSE, warning = FALSE, echo = FALSE}
library(cowplot)
library(kableExtra)
library(caret)
library(dplyr)
source("functions.R")
dataPath                          <- file.path(getwd(), "data")
folderToSavePlots                 <- file.path(getwd(), "plots")
folderToSavecalculations          <- file.path(getwd(), "calculations")
folderToSavePlotsSelectedFeatures <- file.path(folderToSavePlots, "selectedFeatures")
folderToSavecalculations          <- file.path(folderToSavePlots, "..", "calculations")

load(file = file.path(folderToSavecalculations, "resultsOfIV_allvariables.Rdata"))
load(file = file.path(folderToSavecalculations, "iv_in_variable_bins_plots.Rdata"))
load(file = file.path(folderToSavecalculations, 'iVForSelectedcontinuousVariablesWithChoosenBins.Rdata'))
load(file = file.path(folderToSavecalculations, "listOfSeletedVariables.Rdata"))
load(file.path(folderToSavecalculations, "categorisationVariableParametrs.Rdata"))
load(file = file.path(dataPath, "dataNew.Rdata"))
load(file = file.path(dataPath, "dataTrainWithNewFeatures.Rdata"))
load(file = file.path(folderToSavecalculations, "own_choosen_variables_using_owe.Rdata")) ##dane do modelu logistycznego, gdzie sama wybralam bins do 
load(file = file.path(folderToSavecalculations, "plots_iv_in_time_for_choosen_variables.Rdata"))
load(file = file.path(folderToSavePlots, "listOfPlotsTimeSeries.Rdata"))
  variablesFromFeature        <<- c("sub_grade", "grade", "int_rate", "installment", "total_pymnt", "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee", "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "initial_list_status")
  variablesAnotherToDelete    <<- c("id", "member_id", "issue_d", "loan_status", "funded_amnt_inv", "term", "verification_status", "funded_amnt", "group", "last_credit_pull_d", "collections_12_mths_ex_med", "acc_now_delinq")
  
groupedVariables <- c("quarter", "month")
variablesName <- names(dataTrainWithNewFeatures)[which(!names(dataTrainWithNewFeatures) %in% groupedVariables)]
continuous_variables <- listOfSeletedVariables$continuous
discrete_variables <- listOfSeletedVariables$discrete
dataTrainWithNewFeatures <- dataTrainWithNewFeatures[, which(!names(dataTrainWithNewFeatures) %in% c("quarter", "month"))]
```


## Model building

1. Logistic Regression
    
    + With weight of evidence coding variables
    
        + Feature selecion using Information value (IV) and weight of evidence (Woe)

IV values:        
```{r iv, message = FALSE, warning = FALSE, echo = FALSE}
cowplot::plot_grid(results$iv_for_all_variables_plot) 

  results$information_table$Summary %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
cowplot::plot_grid(plotlist =  plots_of_iv_and_bins)  
```

</br>
</br>

Woe values:

```{r woe, message = FALSE, warning = FALSE, echo = FALSE}

cowplot::plot_grid(plotlist =  results$plotsOfWoe[1:4])
cowplot::plot_grid(plotlist =  results$plotsOfWoe[5:8])
cowplot::plot_grid(plotlist =  results$plotsOfWoe[9:12])
cowplot::plot_grid(plotlist =  results$plotsOfWoe[13:16])
cowplot::plot_grid(plotlist =  results$plotsOfWoe[17:20])
cowplot::plot_grid(plotlist =  results$plotsOfWoe[21:23])
```






